### ISSUE TITLE
nothing work

### ISSUE THREAD

**Issue by CodingBDX** [clicky4u/Tiktok-Booster#1]
not work at all

process complet!! in green but nothing work.

**Comment by clicky4u** [comment]
It still works, brother. After you complete the Captcha and it's successfully submitted, you need to wait for 2 minutes. If you don’t see '☣︎ 1000 views sent to the video,' it means something went wrong with the Captcha, and you need to try again until you see '☣︎ 1000 views sent to the video.' That means it worked.

**Comment by clicky4u** [comment]
> not work at all
> 
> process complet!! in green but nothing work.

It still works, brother. After you complete the Captcha and it's successfully submitted, you need to wait for 2 minutes. If you don’t see '☣︎ 1000 views sent to the video,' it means something went wrong with the Captcha, and you need to try again until you see '☣︎ 1000 views sent to the video.' That means it worked.

**Comment by CodingBDX** [comment]
![tmprnrlx3i0](https://github.com/user-attachments/assets/4fee3b33-eb7a-4046-9364-f6e36b28cebb)

that the capchat

**Comment by clicky4u** [comment]
> ![tmprnrlx3i0](https://private-user-images.githubusercontent.com/93124252/377506580-4fee3b33-eb7a-4046-9364-f6e36b28cebb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzU0NzYsIm5iZiI6MTcyOTE3NTE3NiwicGF0aCI6Ii85MzEyNDI1Mi8zNzc1MDY1ODAtNGZlZTNiMzMtZWI3YS00MDQ2LTkzNjQtZjZlMzZiMjhjZWJiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNjUzNTAyYTNlNjkxY2MyM2Y4ZWQzZDFiNDBmNjIyOGI4NDIzMzMyYjYyNWQ4NTc5OTRiYTljNjBmZjUwZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9vOEiLzV8esi6SICmC3KUGEfn0Cg2fWnqvnm_tYAMvk)
> 
> that the capchat

you need to try again until you see '☣︎ 1000 views sent to the video.' That means it worked.

**Comment by CodingBDX** [comment]
but it's the same captcha, look the immage, it's that???????

**Comment by clicky4u** [comment]
> but it's the same captcha, look the immage, it's that???????

captcha is not the same.

**Comment by CodingBDX** [comment]
look that send that image!!!
![tmprnrlx3i0](https://github.com/user-attachments/assets/d264e5bf-c4ce-499f-a8e2-440a1f863315)

**Comment by clicky4u** [comment]
> look that send that image!!! ![tmprnrlx3i0](https://private-user-images.githubusercontent.com/93124252/377515027-d264e5bf-c4ce-499f-a8e2-440a1f863315.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzY0ODIsIm5iZiI6MTcyOTE3NjE4MiwicGF0aCI6Ii85MzEyNDI1Mi8zNzc1MTUwMjctZDI2NGU1YmYtYzRjZS00OTlmLWE4ZTItNDQwYTFmODYzMzE1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjYzMWUwZWQ0NjM4M2VlNzQzMTUxZTMxODBlYTc4YTgyOWU5ZGIyOTFhM2MzNzVkMzg5ZGU2ZWNiNzJjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hY_fGDPQkwPkdj38v9wS6fFNEm6TiemLXewnM2Cwgqo)

c

**Comment by clicky4u** [comment]
> look that send that image!!! ![tmprnrlx3i0](https://private-user-images.githubusercontent.com/93124252/377515027-d264e5bf-c4ce-499f-a8e2-440a1f863315.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzY0ODIsIm5iZiI6MTcyOTE3NjE4MiwicGF0aCI6Ii85MzEyNDI1Mi8zNzc1MTUwMjctZDI2NGU1YmYtYzRjZS00OTlmLWE4ZTItNDQwYTFmODYzMzE1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjYzMWUwZWQ0NjM4M2VlNzQzMTUxZTMxODBlYTc4YTgyOWU5ZGIyOTFhM2MzNzVkMzg5ZGU2ZWNiNzJjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hY_fGDPQkwPkdj38v9wS6fFNEm6TiemLXewnM2Cwgqo)

delete it and try again

**Comment by CodingBDX** [comment]
i see, i don't use windows, i use linux onlly

**Comment by clicky4u** [comment]
> i see, i don't use windows, i use linux onlly
it work with linux too because I’m using with Linux

**Comment by CodingBDX** [comment]
`Exception in thread Thread-2 (listen_for_stop)Exception in thread :
Thread-1 (start_automation)Traceback (most recent call last):
:
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
      File "/usr/lib/python3.10/threading.py", line 953, in run
self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anto/tiktok/Tiktok-Booster/v5.py", line 166, in listen_for_stop
    self._target(*self._args, **self._kwargs)
      File "/home/anto/tiktok/Tiktok-Booster/v5.py", line 100, in start_automation
keyboard.wait('ctrl+z')
      File "/home/anto/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 881, in wait
driver = webdriver.Chrome(service=service, options=chrome_options)
  File "/home/anto/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
        remove = add_hotkey(hotkey, lambda: lock.set(), suppress=suppress, trigger_on_release=trigger_on_release)super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",

  File "/home/anto/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 639, in add_hotkey
  File "/home/anto/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
        self.service.start()_listener.start_if_necessary()

  File "/home/anto/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
      File "/home/anto/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self.init()
      File "/home/anto/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 196, in init
self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1738, in _execute_child
    _os_keyboard.init()    
and os.path.dirname(executable)  File "/home/anto/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 113, in init

  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)    
build_device()TypeError
:   File "/home/anto/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
expected str, bytes or os.PathLike object, not NoneType    
ensure_root()
Process completed!
  File "/home/anto/.local/lib/python3.10/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root

    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
`

if i use root, that not work at all
